### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/net/http/HttpClient

### ISSUE THREAD

**Issue by hungnb94** [Thoroldvix/youtube-transcript-api#22]
Can not run on android project

### Steps to reproduce
* Open an android project
* Add youtube-transcript-api dependency
* Run project

#### Actual result:
Got exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/net/http/HttpClient

#### Expected result:
Get transcript success

#### Stacktrace:
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/net/http/HttpClient;
at io.github.thoroldvix.internal.DefaultYoutubeClient.<init>(DefaultYoutubeClient.java:22)
at io.github.thoroldvix.internal.TranscriptApiFactory.createDefault(TranscriptApiFactory.java:23)
at com.hb.myapplication.MainActivity.getTranscript(MainActivity.kt:89)
at com.hb.myapplication.MainActivity.onCreate(MainActivity.kt:85)
at android.app.Activity.performCreate(Activity.java:8538)
at android.app.Activity.performCreate(Activity.java:8502)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1440)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3890)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4055)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:211)
at android.os.Looper.loop(Looper.java:300)
at android.app.ActivityThread.main(ActivityThread.java:8395)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by hungnb94** [comment]
I think you should use HttpUrlConnection or Okhttp instead of HttpClient

**Comment by Thoroldvix** [comment]
Hey, java HTTP client is part of java 11, are you using lower version? It is also possible to overwrite default client that is used by implementing YoutubeClient interface and the passing it to TranscriptApi factory method, you can check it here https://github.com/Thoroldvix/youtube-transcript-api#youtubeclient-customization

**Comment by Thoroldvix** [comment]
Here is example implementation using OkHttp 

```java 
public class OkHttpYoutubeClient implements YoutubeClient {

    private final OkHttpClient client;

    public OkHttpYoutubeClient(OkHttpClient client) {
        this.client = client;
    }

    @Override
    public String get(String url, Map<String, String> headers) throws TranscriptRetrievalException {
        Request request = new Request.Builder()
                .headers(Headers.of(headers))
                .url(url)
                .build();

        return sendGetRequest(request);
    }

    @Override
    public String get(YtApiV3Endpoint endpoint, Map<String, String> params) throws TranscriptRetrievalException {
        Request request = new Request.Builder()
                .url(endpoint.url() + "?" + createParamsString(params))
                .build();

        return sendGetRequest(request);
    }

    @NotNull
    private String sendGetRequest(Request request) throws TranscriptRetrievalException {
        try (okhttp3.Response response = client.newCall(request).execute()) {
            if (response.isSuccessful()) {
                ResponseBody body = response.body();
                if (body == null) {
                    throw new TranscriptRetrievalException("Response body is null");
                }
                return body.string();
            }
        } catch (IOException e) {
            throw new TranscriptRetrievalException("Failed to retrieve data from YouTube", e);
        }
        throw new TranscriptRetrievalException("Failed to retrieve data from YouTube");
    }

    private static String createParamsString(Map<String, String> params) {
        StringBuilder paramString = new StringBuilder();

        for (Map.Entry<String, String> entry : params.entrySet()) {
            String value = entry.getValue();
            paramString.append(entry.getKey()).append("=").append(value).append("&");
        }

        paramString.deleteCharAt(paramString.length() - 1);
        return paramString.toString();
    }
}

**Comment by hungnb94** [comment]
> Hey, java HTTP client is part of java 11, are you using lower version? It is also possible to overwrite default client that is used by implementing YoutubeClient interface and the passing it to TranscriptApi factory method, you can check it here https://github.com/Thoroldvix/youtube-transcript-api#youtubeclient-customization

I set compile options to java 11, it still not working. Because Android SDK does not include everything in Java SDK.
Therefore I suggest you to use okhttp or httpurlconnnection instead.
But thank you your solution [customization](https://github.com/Thoroldvix/youtube-transcript-api#youtubeclient-customization) work perfect 🥳
